create database insurance;
\c insurance;

CREATE USER webapp WITH PASSWORD 'hello';


create table clients(
	  id 		 int NOT NULL PRIMARY KEY
	, first_name varchar(127)
	, last_name  varchar(127)
	, patronymic varchar(127)
	, birth_date 	  date
	, passport_series int
	, passport_number int
	, unique (passport_series, passport_number)
);
grant select, insert, update
on clients
to webapp;

drop table contracts; drop table estate_objects;
create table estate_objects(
	  id int GENERATED BY DEFAULT AS IDENTITY NOT NULL UNIQUE
	
	, country  varchar(127) NOT NULL
	, region   varchar(127) NOT NULL 	-- область
	, locality varchar(127) NOT NULL 	-- нас. пункт
	, street   varchar(127) NOT NULL 
	, street_num int		 NOT NULL 
	, apt_num 	 int		 NOT NULL 	-- номер квартиры
	
	, mail_index  varchar(15)
	, district    varchar(127)			-- район
	, housing 	  varchar(35)			-- корпус
	, building 	  varchar(35)			-- строение
	
	, estate_type varchar(35)
	, area 		  float 
	, build_year int
	, PRIMARY KEY (country, region, locality, street, street_num, apt_num)
);
grant select, insert, update
on estate_objects
to webapp;


create table contracts(
	  num 			    int NOT NULL PRIMARY KEY
	, client_id 	    int references clients(id)
	, estate_object_id  int references estate_objects(id)
	, contract_date 	date
	, begin_date 		date
	, end_date   		date
	, ensurance_sum 	float
	, premium 			float
	, premium_calc_date date
	, note 				varchar(2000)
);
grant select, insert, update
on contracts
to webapp;


create table area_coeff(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, area_lb float
	, area_ub float
	, coefficient float
);
grant select
on area_coeff
to webapp;

create table build_year_coeff(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, build_year_lb int
	, build_year_ub int
	, coefficient float
);
grant select
on build_year_coeff
to webapp;

create table estate_type_coeff(
	  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY
	, estate_type varchar(35)
	, coefficient float
);
grant select
on estate_type_coeff
to webapp;


insert into area_coeff(area_lb, area_ub, coefficient)
values
	  (null, 49.99, 1.2)
	, (50.0, 100.0, 1.5)
	, (100.01, null, 2.0)
;

insert into build_year_coeff(build_year_lb, build_year_ub, coefficient)
values
	  (null, 1999, 1.3)
	, (2000, 2014, 1.6)
	, (2015, null, 2.0)
;

insert into estate_type_coeff(estate_type, coefficient)
values
	  ('Комната', 1.3)
	, ('Дом', 1.5)
	, ('Квартира', 1.7)
;
